### ISSUE TITLE
Buttons work, pen doesn't for H950p

### ISSUE THREAD

**Issue by A4Abhiraj** [dannytaylor/pinspiroy#2]
The debug.py correctly captures coordinates of the pen though. 
I'm on Ubuntu 17.10 .
Please help!

**Comment by dannytaylor** [comment]
This is a different tablet than this script has been written for, you can try your luck with the [950 fork](https://github.com/mhdchehade/pinspiroy-950). If your device is similar to the G10T it won't work on releases past Ubuntu 16.04 in my testing, see the foreword in the readme for a brief description of the problem.

**Comment by A4Abhiraj** [comment]
I already read the foreword. I'm not calling this an issue.  But the fact that debug.py notes the coordinates, I thought it should be possible to write a wrapper to make this work for 950p.

**Comment by dannytaylor** [comment]
Okay, I should expand on the issue. Past 16.04 the issue isn't reading the USB data or getting mouse coordinates, it's with *uinput* and STYLUS/PEN inputs not being able to be emulated at the same time as coordinates and pressure data. I was able to get the pen to move around on the screen and send mouse clicks, but not pressure and stylus clicks. 

I spent a lot of time trying to debug and fix this issue, but for some reason the only thing that worked was reverting to 16.04 which would indicate it's probably a problem with something beyond my knowledge level.

You could get everything except pen pressure/presses working if wanted (buttons, mouse movement, trackpad), but it wouldn't be any good for drawing unfortunately.

**Comment by A4Abhiraj** [comment]
Ah ! Alright I'll dig into this over the weekend and see if I get something ! Till then I should try that fork you mentioned. In fact I landed here from that fork. Thanks and I'll keep you posted!
