### ISSUE TITLE
Found workaround for Ubuntu 18.04 (add to readme.md?)

### ISSUE THREAD

**Issue by KaiJan57** [dannytaylor/pinspiroy#6]
While this driver works flawlessly on Ubuntu 16.04, Ubuntu 18.04 appears to have issues with virtual graphic tablets by default. To make this driver work on the new Ubuntu version, just edit/create a file `"/etc/udev/hwdb.d/61-evdev-local.hwdb"`
and append the following content:
```
evdev:name:pinspiroy-pen*
 EVDEV_ABS_00=::5080
 EVDEV_ABS_01=::5080
```
now issue the following command: `sudo systemd-hwdb update` to apply the changes.
After all this is done, just start the driver and your tablet should be working just fine!

**Comment by dannytaylor** [comment]
Awesome, thank you! I've updated the readme with this info. This should also fix the same problem on Arch and other distros newer than Ubuntu 16.04, though I can't test it at the moment.
